export const ENT = {
  hub: [
    {
      t: "portal",
      x: 22,
      y: 9,
      to: "process_plains",
      tx: 3,
      ty: 5,
      label: "⚙️ Process Plains",
    },
    {
      t: "portal",
      x: 1,
      y: 9,
      to: "archive_city",
      tx: 3,
      ty: 5,
      label: "🏛️ Archive City",
    },
    {
      t: "portal",
      x: 10,
      y: 13,
      to: "memory_caverns",
      tx: 10,
      ty: 9,
      label: "🧠 Memory Caverns",
    },
    {
      t: "portal",
      x: 14,
      y: 18,
      to: "sandbox",
      tx: 15,
      ty: 15,
      label: "🔨 The Workshop",
    },
    {
      t: "npc",
      x: 10,
      y: 5,
      em: "👴",
      name: "Elder Kernel",
      col: "#f0883e",
      lines: [
        "Welcome, young process! I am Elder Kernel, guardian of this Hub.",
        "Three portals lead to OS regions. A fourth leads to the Workshop.",
        "EAST ➡️ Process Plains — CPU scheduling and process lifecycle.",
        "WEST ⬅️ Archive City — Files, inodes, and permissions.",
        "SOUTH ⬇️ Memory Caverns — Pages, frames, and virtual memory.",
        "The south path also leads to 🔨 The Workshop — build anything you want!",
        "Press TAB for the World Map, ESC for Settings. Now go explore!",
      ],
    },
    {
      t: "npc",
      x: 11,
      y: 6,
      em: "👴",
      name: "Elder Kernel Jr. ",
      col: "#f0883e",
      lines: [
        "Welcome, young process! I am Elder Kernel, guardian of this Hub.",
        "Three portals lead to OS regions. A fourth leads to the Workshop.",
        "EAST ➡️ Process Plains — CPU scheduling and process lifecycle.",
        "WEST ⬅️ Archive City — Files, inodes, and permissions.",
        "SOUTH ⬇️ Memory Caverns — Pages, frames, and virtual memory.",
        "The south path also leads to 🔨 The Workshop — build anything you want!",
        "Press TAB for the World Map, ESC for Settings. Now go explore!",
      ],
    },
    {
      t: "npc",
      x: 18,
      y: 5,
      em: "🧚",
      name: "Interrupt Fairy",
      col: "#3fb950",
      lines: [
        "Hey! I'm the Interrupt Fairy! ✨",
        "When a key is pressed, I send a HARDWARE INTERRUPT to the CPU!",
        "The CPU saves its state, runs my handler, then resumes.",
        "Without me, the CPU would have to POLL every device. So wasteful!",
      ],
      wan: true,
      wr: 3,
    },
    {
      t: "npc",
      x: 5,
      y: 11,
      em: "🐱",
      name: "Page Cat",
      col: "#a371f7",
      lines: [
        "*purr* I used to live in the Memory Caverns...",
        "They evicted me. 'Least Recently Used,' they said.",
        "If you visit, watch out. Nobody is safe from page replacement.",
      ],
      wan: true,
      wr: 3,
    },
    {
      t: "npc",
      x: 16,
      y: 8,
      em: "💂",
      name: "Mutex Guard",
      col: "#e74c3c",
      lines: [
        "HALT. Only ONE thread may enter at a time.",
        "This is mutual exclusion. I am the mutex lock.",
      ],
    },
    { t: "chest", x: 3, y: 2, id: "h1" },
    { t: "chest", x: 24, y: 2, id: "h2" },
    { t: "chest", x: 20, y: 15, id: "h3" },
    {
      t: "sign",
      x: 20,
      y: 5,
      text: "EAST → Process Plains: CPU scheduling and process management.",
    },
    {
      t: "sign",
      x: 4,
      y: 5,
      text: "← WEST: Archive City — Files, directories, inodes, permissions.",
    },
    {
      t: "sign",
      x: 10,
      y: 12,
      text: "↓ SOUTH: Memory Caverns — Paging, TLB, page replacement.",
    },
    {
      t: "sign",
      x: 14,
      y: 17,
      text: "↓ The Workshop: Build ANYTHING. Your OS, your rules.",
    },
  ],
  process_plains: [
    { t: "portal", x: 1, y: 5, to: "hub", tx: 20, ty: 9, label: "🏠 The Hub" },
    {
      t: "npc",
      x: 8,
      y: 3,
      em: "⚡",
      name: "Scheduler Prime",
      col: "#e74c3c",
      master: true,
      lines: [
        "I am Scheduler Prime! I decide which process gets the CPU.",
        "ROUND ROBIN: fair time slices. But context switches cost time!",
        "SHORTEST JOB FIRST: minimizes avg wait. Long jobs can STARVE.",
        "PRIORITY: urgent first. Needs AGING to prevent starvation.",
        "Ready? Schedule some processes!",
      ],
      quest: {
        id: "q_sched",
        name: "Scheduling Trial",
        xp: 200,
        sim: "scheduler",
      },
    },
    {
      t: "npc",
      x: 12,
      y: 12,
      em: "👶",
      name: "Child Process",
      col: "#f0883e",
      lines: [
        "I was born from fork()! Parent gave me a COPY of everything.",
        "fork() returns 0 to me, my PID to the parent.",
        "After fork, I called exec() to become a new program!",
        "A rogue process is eating all CPU! Can you find it?",
      ],
      quest: {
        id: "q_kill",
        name: "Rogue Process Hunt",
        xp: 180,
        sim: "process_kill",
      },
    },
    {
      t: "npc",
      x: 6,
      y: 10,
      em: "🧟",
      name: "Zombie Process",
      col: "#777",
      lines: [
        "Uuugh... I finished... but parent never called wait()...",
        "I am a ZOMBIE. Please tell my parent to reap me...",
      ],
      wan: true,
      wr: 3,
    },
    { t: "chest", x: 3, y: 1, id: "p1" },
    { t: "chest", x: 24, y: 14, id: "p2" },
    {
      t: "sign",
      x: 10,
      y: 5,
      text: "READY queue → Scheduler picks → RUNS on CPU → Context switch saves PCB.",
    },
  ],
  memory_caverns: [
    {
      t: "portal",
      x: 10,
      y: 9,
      to: "hub",
      tx: 10,
      ty: 12,
      label: "🏠 The Hub",
    },
    {
      t: "npc",
      x: 14,
      y: 5,
      em: "💎",
      name: "TLB Crystal",
      col: "#58a6ff",
      master: true,
      lines: [
        "I am the TLB — a page table cache.",
        "Without me, every access needs TWO lookups!",
        "A TLB hit = ONE fast lookup. Miss = expensive page table walk.",
        "Can you handle page requests with minimal faults?",
      ],
      quest: {
        id: "q_page",
        name: "Page Fault Crisis",
        xp: 220,
        sim: "page_fault",
      },
    },
    {
      t: "npc",
      x: 6,
      y: 7,
      em: "📄",
      name: "Wandering Page",
      col: "#ccc",
      lines: [
        "I keep getting SWAPPED between RAM and disk!",
        "FIFO: oldest out. LRU: least recently used out.",
      ],
      wan: true,
      wr: 5,
    },
    { t: "chest", x: 2, y: 2, id: "m1" },
    { t: "chest", x: 25, y: 2, id: "m2" },
    {
      t: "sign",
      x: 4,
      y: 5,
      text: "Pages map to Frames via Page Table. Virtual → Physical.",
    },
  ],
  archive_city: [
    { t: "portal", x: 1, y: 5, to: "hub", tx: 3, ty: 9, label: "🏠 The Hub" },
    {
      t: "npc",
      x: 8,
      y: 6,
      em: "📋",
      name: "Inode Inspector",
      col: "#f39c12",
      master: true,
      lines: [
        "Every file has an INODE — its true identity!",
        "Inodes store: size, permissions, timestamps, block pointers.",
        "Filenames are in directory entries, NOT the inode.",
        "Can you set permissions correctly?",
      ],
      quest: {
        id: "q_perm",
        name: "Permission Lockdown",
        xp: 200,
        sim: "permissions",
      },
    },
    {
      t: "npc",
      x: 18,
      y: 7,
      em: "📝",
      name: "Journal Keeper",
      col: "#3fb950",
      lines: [
        "I write to the JOURNAL before applying changes.",
        "Crash mid-write? Replay journal. WRITE-AHEAD LOGGING.",
      ],
      wan: true,
      wr: 3,
    },
    {
      t: "npc",
      x: 14,
      y: 12,
      em: "🔐",
      name: "Mutex Lord",
      col: "#9b59b6",
      lines: [
        "LOCKED or UNLOCKED. Only one thread holds me.",
        "No lock → RACE CONDITION → data corruption!",
      ],
      quest: {
        id: "q_mutex",
        name: "Race Condition",
        xp: 250,
        sim: "mutex_sim",
      },
    },
    { t: "chest", x: 24, y: 1, id: "a1" },
    { t: "chest", x: 24, y: 17, id: "a2" },
  ],
  sandbox: [
    {
      t: "portal",
      x: 15,
      y: 0,
      to: "hub",
      tx: 14,
      ty: 17,
      label: "🏠 The Hub",
    },
    {
      t: "npc",
      x: 15,
      y: 3,
      em: "🔨",
      name: "Builder Bot",
      col: "#f0883e",
      lines: [
        "Welcome to the Workshop! Here you can BUILD anything.",
        "Press B to open the build palette. Click tiles to place blocks.",
        "Build your own OS architecture, a CPU diagram, or whatever you want!",
        "Press B again to close build mode. Right-click to erase.",
        "Your creations are saved automatically!",
      ],
    },
    {
      t: "sign",
      x: 12,
      y: 3,
      text: "🔨 THE WORKSHOP — Press B to build. Click to place. Right-click to erase.",
    },
  ],
};
