export const regions = [
  {
    id: "hub",
    name: "The Hub",
    icon: "🏠",
    x: 50,
    y: 35,
    col: "#58a6ff",
    desc: "Central hub connecting all regions. Talk to Elder Kernel to get started.",
    quests: [],
  },
  {
    id: "process_plains",
    name: "Process Plains",
    icon: "⚙️",
    x: 85,
    y: 35,
    col: "#e74c3c",
    desc: "Master CPU scheduling, process lifecycle, fork(), and context switching.",
    quests: ["q_sched", "q_kill"],
    npcs: ["Scheduler Prime", "Child Process", "Zombie Process"],
  },
  {
    id: "memory_caverns",
    name: "Memory Caverns",
    icon: "🧠",
    x: 50,
    y: 65,
    col: "#58a6ff",
    desc: "Navigate paging, TLB caching, page replacement, and virtual memory.",
    quests: ["q_page"],
    npcs: ["TLB Crystal", "Wandering Page"],
  },
  {
    id: "archive_city",
    name: "Archive City",
    icon: "🏛️",
    x: 15,
    y: 35,
    col: "#f39c12",
    desc: "Explore files, inodes, permissions, journaling, and directory structures.",
    quests: ["q_perm", "q_mutex"],
    npcs: ["Inode Inspector", "Journal Keeper", "Mutex Lord"],
  },
  {
    id: "sandbox",
    name: "The Workshop",
    icon: "🔨",
    x: 50,
    y: 88,
    col: "#f0883e",
    desc: "Your creative space. Press B to build anything with 18 different tiles.",
    quests: [],
  },
];
export const connections = [
  ["hub", "process_plains"],
  ["hub", "archive_city"],
  ["hub", "memory_caverns"],
  ["hub", "sandbox"],
];
